export const brands = [
  { label: 'Americolor', value: 'Americolor' },
  { label: 'BakeKing', value: 'BakeKing' },
  { label: 'Bakeland', value: 'Bakeland' },
  { label: 'Bakels', value: 'Bakels' },
  { label: "Baker's Delight", value: "Baker's Delight" },
  { label: 'Bakeware', value: 'Bakeware' },
  { label: 'Blossoms', value: 'Blossoms' },
  { label: 'Candy', value: 'Candy' },
  { label: 'Caroline Cupcakes', value: 'Caroline Cupcakes' },
  { label: 'Clovers', value: 'Clovers' },
  { label: 'Collata', value: 'Collata' },
  { label: 'Dairyland', value: 'Dairyland' },
  { label: 'Dr Gusto', value: 'Dr Gusto' },
  { label: 'Easy Bake Supplies Limited', value: 'Easy Bake Supplies Limited' },
  { label: "Elly's", value: "Elly's" },
  { label: 'Essence', value: 'Essence' },
  { label: 'Eurocas', value: 'Eurocas' },
  { label: 'Europea', value: 'Europea' },
  { label: 'Flour', value: 'Flour' },
  { label: 'Hamilworth', value: 'Hamilworth' },
  { label: 'Kenafric Industries', value: 'Kenafric Industries' },
  { label: 'KSL', value: 'KSL' },
  { label: 'Lato', value: 'Lato' },
  { label: 'Lyons', value: 'Lyons' },
  { label: 'Maimun', value: 'Maimun' },
  { label: 'Nestle', value: 'Nestle' },
  { label: 'Pradip', value: 'Pradip' },
  { label: 'Pristine', value: 'Pristine' },
  { label: 'Puratos', value: 'Puratos' },
  { label: 'Rainbow dust', value: 'Rainbow dust' },
  { label: 'Strawberries', value: 'Strawberries' },
  { label: 'Sugarflair', value: 'Sugarflair' },
  { label: 'Top Lure', value: 'Top Lure' },
  { label: 'Tri Clover', value: 'Tri Clover' },
  { label: 'Ustam', value: 'Ustam' },
  { label: 'Wilton', value: 'Wilton' },
  { label: 'Zeelandia', value: 'Zeelandia' },
  { label: 'Zesta', value: 'Zesta' },
]
